<?php

namespace Shared\DTO\Elasticsearch;

use Shared\DTO\DTOAbstract;

class CreateElasticsearchDTO extends CommonElasticSearchDTO
{
    public function register(?string $index, ?string $type = 'doc', ?array $body = []): CommonElasticSearchDTO
    {
        return parent::register($index, $type, $body); // TODO: Change the autogenerated stub
    }
}
