<?php

namespace Shared\DTO\Elasticsearch;

use Shared\DTO\DTOAbstract;

class SearchElasticsearchDTO extends CommonElasticSearchDTO
{
    public function register(?string $index, ?string $type = 'doc', ?array $body = []): CommonElasticSearchDTO
    {
        $body = [
            'query' => [
                'match' => $body
            ]
        ];

        return parent::register($index, $type, $body); // TODO: Change the autogenerated stub
    }

}
